### ISSUE TITLE
Article suggestions for FIM and max_token decoding

### ISSUE THREAD

**Issue by nielstron** [Saibo-creator/Awesome-LLM-Constrained-Decoding#12]
I wrote two short articles about leveraging context-free language based decoding techniques for
- fill in the middle decoding: https://blog.nielstron.de/2024/08/14/leveraging-constrained-sampling-for-fill-in-the-middle-code-completion/
- max_token decoding: https://blog.nielstron.de/2024/08/13/proper-well-formedness-for-finite-llm-sampling/

There are also more very useful blog posts on the topic such as this one:
https://vivien000.github.io/blog/journal/llm-decoding-with-regex-constraints.html

**Comment by Saibo-creator** [comment]
@nielstron  Thanks for the suggestions !
